{% set name = "constantdict" %}
{% set version = "2025.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matthiasdiener/constantdict/archive/v{{ version }}.tar.gz
  sha256: 79fef40f895faaf78ad63c0c7d6c35523d913025971a8aeff4d3bc9dbf9835ca

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - importlib-metadata
    - python >={{ python_min }}

test:
  imports:
    - constantdict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matthiasdiener/constantdict
  summary: An immutable dict class.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
    - inducer
