{% set name = "constantdict" %}
{% set version = "2025.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matthiasdiener/constantdict/archive/v{{ version }}.tar.gz
  sha256: 4660a12660a61efb7bf5c2ae152362f5bbc158d4ebdf4661614c98f25db71efc

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - constantdict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matthiasdiener/constantdict
  summary: An immutable dict class.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
    - inducer
